title: Simon Reinkemeier
logo: /assets/img/photo_main.jpg
description: Computer Science student at KIT and Software Engineer.
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
